optimised

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,24 +5,24 @@ set -e
 MX2S="mx2s-tiltkeys-linux"
 
 # checks if main.rs exists, before even running build and install script
-[ -f src/main.rs &>${N} ] || (echo -e "main.rs not found! ): \nrun in original dir" && exit 1)
+[ -f src/main.rs &>${N} ] || (echo -e "main.rs not found! ): \nrun cloned dir" && exit 1)
 systemctl --user is-active ${MX2S}.service &>${N} && systemctl --user stop ${MX2S}.service || :
 
 GREEN="\x1b[38;5;49m"
 YELW="\x1b[38;5;229m"
 FEND="\x1b[0m"
 
-echo -e "${YELW} [1/5]${FEND} \n building rust binary"
+echo -e "${YELW} [1/5]${FEND} \n building binary"
 cargo build --release -q 2>./build-log.txt
 
 if [ ! -d "$HOME/.config/mx2s-tiltkeys" ]; then
-  echo "${GREEN} creating base config ${FEND}"
+  echo "${GREEN} creating config ${FEND}"
   mkdir -p "$HOME/.config/mx2s-tiltkeys" 
   cp ./config.json "$HOME/.config/mx2s-tiltkeys/config.json"
 fi
 
 sudo cp target/release/${MX2S} /usr/local/bin/${MX2S}
-echo -e "${YELW} [2/5] ${FEND} \n installed bin to /usr/local/bin"
+echo -e "${YELW} [2/5] ${FEND} \n installed to /usr/local/bin"
 
 if ! groups "$USER" | grep -q "\binput\b"; then
   sudo usermod -aG input "$USER"
@@ -31,7 +31,7 @@ fi
 echo "uinput" | sudo tee /etc/modules-load.d/uinput.conf > ${N}
 echo 'z /dev/uinput 0660 root input - -' | sudo tee /etc/tmpfiles.d/uinput.conf > ${N}
 echo 'KERNEL=="uinput", MODE:="0660", GROUP="input", OPTIONS+="static_node=uinput"' | sudo tee /etc/udev/rules.d/99-uinput.rules > ${N}
-echo -e "${YELW} [3/5] ${FEND} \n configured uinput perms and input group"
+echo -e "${YELW} [3/5] ${FEND} \n setup perms"
 
 echo -e "${YELW} [4/5] ${FEND} \n applying hardware perm changes"
 sudo systemd-tmpfiles --create /etc/tmpfiles.d/uinput.conf
@@ -40,20 +40,7 @@ sudo udevadm control --reload-rules && sudo udevadm trigger
 mkdir -p "$HOME/.config/systemd/user"
 echo -e "${YELW} [5/5]${FEND}\n created and enabled as service"
 
-cat << EOF > "$HOME/.config/systemd/user/${MX2S}.service"
-[Unit]
-Description=MX2S-tiltwheel daemon
-After=graphical-session.target
-
-[Service]
-ExecStart=/usr/local/bin/${MX2S}
-Restart=always
-RestartSec=10
-
-[Install]
-WantedBy=default.target
-EOF
-
+cp ${MX2S}.service "$HOME/.config/systemd/user/${MX2S}.service"
 
 systemctl --user daemon-reload
 systemctl --user enable --now ${MX2S}.service 2>${N}
